// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzariaM1S09.Models;

#nullable disable

namespace PizzariaM1S09.Migrations
{
    [DbContext(typeof(PizzariaM1S09Context))]
    partial class PizzariaM1S09ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzariaM1S09.Models.Borda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Borda");

                    b.ToTable("Borda", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Massa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Massa");

                    b.ToTable("Massa", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PizzaId")
                        .HasColumnType("int")
                        .HasColumnName("Pizza_Id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("Status_Id");

                    b.HasKey("Id")
                        .HasName("PK__Pedido");

                    b.HasIndex("PizzaId");

                    b.HasIndex("StatusId");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BordaId")
                        .HasColumnType("int")
                        .HasColumnName("Sabores_Id");

                    b.Property<int>("MassaId")
                        .HasColumnType("int")
                        .HasColumnName("Pizza_Id");

                    b.HasKey("Id")
                        .HasName("PK__Pizza");

                    b.HasIndex("BordaId");

                    b.HasIndex("MassaId");

                    b.ToTable("Pizza", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.PizzaSabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PizzaId")
                        .HasColumnType("int")
                        .HasColumnName("Pizza_Id");

                    b.Property<int>("SaborId")
                        .HasColumnType("int")
                        .HasColumnName("Sabores_Id");

                    b.HasKey("Id")
                        .HasName("PK__PizzaSabor");

                    b.HasIndex("PizzaId");

                    b.HasIndex("SaborId");

                    b.ToTable("PizzaSabor", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeSabor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Status");

                    b.ToTable("Sabor", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Status");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Pedido", b =>
                {
                    b.HasOne("PizzariaM1S09.Models.Pizza", "Pizza")
                        .WithMany("Pedidos")
                        .HasForeignKey("PizzaId")
                        .IsRequired()
                        .HasConstraintName("FK__Pizza_Pedido");

                    b.HasOne("PizzariaM1S09.Models.Status", "Status")
                        .WithMany("Pedidos")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Status_Pizza");

                    b.Navigation("Pizza");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Pizza", b =>
                {
                    b.HasOne("PizzariaM1S09.Models.Borda", "Borda")
                        .WithMany("Pizzas")
                        .HasForeignKey("BordaId")
                        .IsRequired()
                        .HasConstraintName("FK__Pizza_Borda");

                    b.HasOne("PizzariaM1S09.Models.Massa", "Massa")
                        .WithMany("Pizzas")
                        .HasForeignKey("MassaId")
                        .IsRequired()
                        .HasConstraintName("FK__Pizza_Massa");

                    b.Navigation("Borda");

                    b.Navigation("Massa");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.PizzaSabor", b =>
                {
                    b.HasOne("PizzariaM1S09.Models.Pizza", "Pizza")
                        .WithMany("PizzasSabores")
                        .HasForeignKey("PizzaId")
                        .IsRequired()
                        .HasConstraintName("FK__Pizza_Sabor");

                    b.HasOne("PizzariaM1S09.Models.Sabor", "Sabor")
                        .WithMany("PizzasSabores")
                        .HasForeignKey("SaborId")
                        .IsRequired()
                        .HasConstraintName("FK__Sabor_Pizza");

                    b.Navigation("Pizza");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Borda", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Massa", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Pizza", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("PizzasSabores");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Sabor", b =>
                {
                    b.Navigation("PizzasSabores");
                });

            modelBuilder.Entity("PizzariaM1S09.Models.Status", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
